export const LOAD_CURRENT_ITERATION = 'LOAD_CURRENT_ITERATION';
export const LOAD_ITERATION = 'LOAD_ITERATION';
export const LOAD_PULL_REQUESTS = 'LOAD_PULL_REQUESTS';
export const LOAD_REPOSITORIES = 'LOAD_REPOSITORIES';
